configuration:
  swagger:
    app: 'Fitness Application'
    description: 'A simple fitness application with workout plans built with Spring Boot'
    developer: 'Kemal Letić'
    email: 'kemal.letic@stu.ibu.edu.ba'

    mailsender:
      default: 'mailgun'

spring:
  data:
    mongodb:
      uri: mongodb+srv://kemalletic:sifra@fitnessapp.g6rciag.mongodb.net/?retryWrites=true&w=majority
      database: fitnesapp

email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandboxfd245e3dc5bb4c7cb406b6fced537364.mailgun.org
    from-email: Fitness Application <mailgun@sandboxfd245e3dc5bb4c7cb406b6fced537364.mailgun.org>
    username: api
    password: 92fc5347544eba3d8636a6f6c6525d77-0a688b4a-c211a02a

security:
  jwt:
    secret: 'ekBz6YTNCcOd2594SkeIBTI1QnDyb7e9uJ0wIUYfy325ChAUCB'