configuration:
  swagger:
    app: 'Fitness Application'
    description: 'A simple fitness application with workout plans built with Spring Boot'
    developer: 'Kemal Letić'
    email: 'kemal.letic@stu.ibu.edu.ba'

    mailsender:
      default: 'mailgun'

spring:
  data:
    mongodb:
      uri: mongodb+srv://kemalletic:kemalletic123@fitness.93iplik.mongodb.net/?retryWrites=true&w=majority

      database: library

email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandbox29278405945b4dc68ec56e4e841715a0.mailgun.org
    from-email: Library System <mailgun@sandbox29278405945b4dc68ec56e4e841715a0.mailgun.org>
    username: api
    password: b6ab4017ca3ca6bf54832afa11bd554e-3750a53b-1f515ec8